Стилизация главной страницы
htmlacademy-htmlcss/1651395-technomart-30 pull request #5
Opened 2021-01-31 13:38 UTC by Kettel1

2021-02-01 21:11 UTC, Kettel1 commented
> ♻️ Я собрал ваш пулреквест. Посмотреть можно [здесь](https://htmlacademy-htmlcss.github.io/1651395-technomart-30/5/).

2021-02-01 21:13 UTC, Kettel1 commented
Случайно закрыл)

2021-02-02 07:12 UTC, Dima-Dim requested changes
Рекомендую пройтись по разметке и оставить только те теги-контейнеры, без которых нельзя либо по смыслу, либо по стилизации.

2021-02-02 07:12 UTC, Dima-Dim commented on catalog.html
> +                            <p class='header_account_personal'>&#183;</p>
Явно не значимый элемент которого не должно быть в разметке.

2021-02-02 07:12 UTC, Dima-Dim commented on catalog.html
> +                            <p class='header_account_name'>
По стайлгайду это интерактивный элемент. И снова лишняя обёртка в виде div-а :)

2021-02-02 07:12 UTC, Dima-Dim commented on catalog.html
> +                            <form form action="https://echo.htmlacademy.ru/" method="post">
Форма в форме это сильно :) И тоже лучше get.

2021-02-02 07:12 UTC, Dima-Dim commented on catalog.html
> +            <div class='container'>
Этот и следующий div-ы не закрыты.
https://validator.w3.org/nu/

2021-02-02 07:15 UTC, Kettel1 commented on catalog.html
> +                            <p class='header_account_personal'>&#183;</p>
Я планировал его сделать через псевдоэлементы, но пока оставил так чтобы не заморачиваться)

2021-02-02 07:19 UTC, Kettel1 commented on index.html
> +                        <svg width="108" height="18" viewBox="0 0 108 18" fill="none"
Мне почему-то показалось что в стайлгайде с этим элементом есть интерактив

2021-02-02 07:21 UTC, Dima-Dim commented on index.html
> +                        <svg width="108" height="18" viewBox="0 0 108 18" fill="none"
Скорее с его контейнером.

2021-02-02 07:22 UTC, Dima-Dim commented on catalog.html
> +                            <p class='header_account_personal'>&#183;</p>
Лучше не оставлять в разметке такое, что бы не забыть убрать и что бы это не влияло на всё остальное. Лучше оставить комментарий в коде, если нужна "заметка" о том что здесь что-то нужно будет доработать.

2021-02-02 07:22 UTC, Kettel1 commented on index.html
> +                            <p class='header_text bookmark'>Закладки:
div вокруг делал для иконок, что-то с ними химичл и пробовал, в итоге все удалил, икноки реализовал подругому а их забыл убрать

2021-02-02 07:25 UTC, Kettel1 commented on index.html
> +    <link href="https://fonts.googleapis.com/css2?family=PT+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap"
косяк) исправлю

2021-02-02 07:26 UTC, Kettel1 commented on index.html
> +                            <p class='header_icon_search'>
тег p здесь для того, чтобы я от него делал псевдоэлемент для иконки, потому-что от тега input сделать его нельзя т.к. он пустой, stackoverflow в деле))

2021-02-02 07:30 UTC, Kettel1 commented on catalog.html
> +                            <form form action="https://echo.htmlacademy.ru/" method="post">
должен был быть блок aside, проворонил момент)

2021-02-02 07:42 UTC, Kettel1 commented on index.html
> +                        <p class='header_inner_text'>Интернет-магазин<br>Строительных материалов<br>и инструментов
забыл дать им наименнование, эти теги для сетки на флексах, если их убрать, ломается сетка,

2021-02-02 07:43 UTC, Kettel1 commented on index.html
> +                        <form action="https://echo.htmlacademy.ru/" method="post">
исправил

2021-02-02 07:43 UTC, Kettel1 commented on catalog.html
> +            <div class='container'>
исправил

2021-02-02 11:04 UTC, Dima-Dim commented on index.html
> +                        <p class='header_inner_text'>Интернет-магазин<br>Строительных материалов<br>и инструментов
От того что уберёшь div на 77-ой строке вообще ничего не изменится. Тоже самое качается div-а на 76-ой. padding-top нужно перенести на div в 75-ой строке, либо на section.

2021-02-02 11:12 UTC, Kettel1 commented on index.html
> +                            <p class='header_icon_search'>
точно, можно и так, заменил)

2021-02-02 14:15 UTC, Kettel1 commented on index.html
> +                        <p class='header_inner_text'>Интернет-магазин<br>Строительных материалов<br>и инструментов
попробую

2021-02-03 16:26 UTC, merged