Стайлгайд
htmlacademy-htmlcss/1651395-technomart-30 pull request #6
Opened 2021-02-06 11:30 UTC by Kettel1

2021-02-08 07:00 UTC, Dima-Dim requested changes
`icon-search-red.svg` цвет можно менять с помощью css.

2021-02-08 07:00 UTC, Dima-Dim commented on js/app.js
> +        services__inner_btn[i].className = services__inner_btn[i].className.replace(" active", "");
Лучше  https://developer.mozilla.org/ru/docs/Web/API/Element/classList

2021-02-09 17:41 UTC, Kettel1 commented on catalog.html
> +                        <label class='header_text bookmark'>Закладки:
А, я уже поправил на тег p, не закомитил новые изменения с выходных

2021-02-09 17:42 UTC, Kettel1 commented on index.html
> +                                        <svg width="15" height="15" viewBox="0 0 15 15" fill="none"
ну... вообще можно через псеводкласс бэкграудом завернуть, лучше через css?

2021-02-09 17:45 UTC, Kettel1 commented on js/app.js
> +    services_content = document.getElementsByClassName("services_content");
Я посидел щас полчаса, поковырялся в документации, попытался исправить код, не смог( я очень плох пока-что в js.  А этот код я просто вставил в лендинг чтобы работала эта функция) а то прям глаз дергался когда видел не рабочий блок

2021-02-09 17:46 UTC, Kettel1 commented on js/app.js
> +    var i, services_content, services__inner_btn;
я когда вставлял код тоже обратил внимания что какие-то свойства, которых не было в тех же тренажерах от академии..

2021-02-09 17:47 UTC, Dima-Dim commented on index.html
> +                                        <svg width="15" height="15" viewBox="0 0 15 15" fill="none"
Да, лучше псевдоэлементом.

2021-02-09 18:40 UTC, Kettel1 commented on index.html
> +                                        <svg width="15" height="15" viewBox="0 0 15 15" fill="none"
передалал)

2021-02-10 07:58 UTC, Dima-Dim commented on css/style.css
> +.manufacturers_link img:active {
`img` вроде не интерактивный элемент :) для того что бы делать на нём `active`

2021-02-10 07:58 UTC, Dima-Dim commented on css/style.css
> +    background-color: #BA2732
https://up.htmlacademy.ru/htmlcss/30/criteries#d30

2021-02-10 07:58 UTC, merged

2021-02-13 20:49 UTC, Kettel1 commented on css/style.css
> +    background-color: #BA2732
исправил все цвета

2021-02-13 20:51 UTC, Kettel1 commented on css/style.css
> +.manufacturers_link img:active {
да, но если я делаю active или hover на теге a, тогда тень начинает себя вести неправильно вместе с opacity, и если на тег li, тоже получается не то, что нужно

2021-02-14 05:46 UTC, Dima-Dim commented on css/style.css
> +.manufacturers_link img:active {
Прям сейчас да, и выглядит это как какой-то костыль. Нужно же разобраться почему так и решить проблему, а не костылять сразу же.

<details>
<summary>Если не разберёшься сам и посмотришь решение, напиши ответом в чём была проблема, своими словами</summary>

```
.manufacturers_link,
.manufacturers_link img {
    display: block;
}

.manufacturers_link:hover {
    -webkit-box-shadow: 0px 10px 20px 4px rgba(0, 0, 0, 0.2);
    -moz-box-shadow: 0px 10px 20px 4px rgba(0, 0, 0, 0.2);
    box-shadow: 0px 10px 20px 4px rgba(0, 0, 0, 0.2);
    transition: box-shadow .2s ease;
}

.manufacturers_link:active {
    opacity: 0.5;
}
```
</details>

2021-02-15 19:40 UTC, Kettel1 commented on css/style.css
> +.manufacturers_link img:active {
аа, у меня тег <а> и <img> строчные элементы (display:inline), поэтому при наведении на .manufacturers_item там был лишь один кусочек от тени внизу, их нужно сделать блочными и элементы растянутся по заданным параметрам, а пока они строчные на них height и width не работает. 

я сперва подумал див вложить, но внутрь строчных нельзя вкладывать блочные)

2021-02-16 04:54 UTC, Dima-Dim commented on css/style.css
> +.manufacturers_link img:active {
Ну хоть что-то тебя останавливает от бесконечного числа контейнеров :)