Оформление контента
htmlacademy-htmlcss/1651395-technomart-30 pull request #7
Opened 2021-02-13 20:57 UTC by Kettel1

Оформил контент так сказать.
1) Сделал одно модальное окно на главной странице
2) Перенес все цвета в переменные
3) Закончил весь стайлгайд
4) Закончил каталог
5) Сделал кастомные чекбоксы и радиокнопки
6) Чуть чуть поправил разметку и css

2021-02-14 17:33 UTC, Dima-Dim requested changes

2021-02-14 17:33 UTC, Dima-Dim commented on index.html
> +    <div class="modal">
section же :)

2021-02-14 17:33 UTC, Dima-Dim commented on index.html
> +                <button class='modal_btn btn'>Отправить</button>
Что-то многовато контейнеров для кнопки.

2021-02-14 17:33 UTC, Dima-Dim commented on catalog.html
> +                            <p class='header_account_name'>Равшан Джамшутович</p>
Похоже на часть предыдущего интерактивного элемента.

2021-02-14 17:33 UTC, Dima-Dim commented on css/style.css
> +    --basic-lightgrey-350: #d7dcde;
https://up.htmlacademy.ru/htmlcss/30/criteries#b15

2021-02-14 17:33 UTC, Dima-Dim commented on css/style.css
> +    ;
?

2021-02-14 17:33 UTC, Dima-Dim commented on css/style.css
> +    padding: 10.7px 25px;
Точности в 1px достаточно.

2021-02-14 17:33 UTC, Dima-Dim commented on css/style.css
> +    ;
?

2021-02-14 17:33 UTC, Dima-Dim commented on css/style.css
> +    cursor: pointer;
Ещё один намёк что это всё же интерактивный элемент.

2021-02-14 17:33 UTC, Dima-Dim commented on css/style.css
> +.proudct_features_btn::after, .proudct_features_btn::before {
С переносом на новую строку читалось бы лучше.

2021-02-14 17:33 UTC, Dima-Dim commented on css/style.css
> +    font-family: PT Sans;
https://up.htmlacademy.ru/htmlcss/30/criteries#b10

2021-02-14 17:33 UTC, Dima-Dim commented on css/style.css
> +    left: 0px;
https://up.htmlacademy.ru/htmlcss/30/criteries#b15

2021-02-14 17:33 UTC, Dima-Dim commented on css/style.css
> +    fill: var(--basic-greylight)
Начали пропадать `;`

2021-02-15 19:06 UTC, Kettel1 commented on index.html
> +    <div class="modal">
точно)

2021-02-15 19:06 UTC, Kettel1 commented on index.html
> +                <button class='modal_btn btn'>Отправить</button>
исправил)

2021-02-15 19:10 UTC, Kettel1 commented on catalog.html
> +                            <p class='header_account_name'>Равшан Джамшутович</p>
не понимаю не много, что тут не так..

2021-02-15 19:10 UTC, Kettel1 commented on css/style.css
> +    --basic-lightgrey-350: #d7dcde;
исправил

2021-02-15 19:12 UTC, Kettel1 commented on css/style.css
> +    ;
Что тут такое? паддинг неправильный или двоеточие лишние?)

2021-02-15 19:13 UTC, Kettel1 commented on catalog.html
> +                            <p class='header_account_name'>Равшан Джамшутович</p>
или при наведении на имя, это считается как кнопка user слева?

2021-02-15 19:15 UTC, Kettel1 commented on css/style.css
> +    fill: var(--basic-greylight)
косяк

2021-02-15 19:22 UTC, Kettel1 commented on css/style.css
> +    cursor: pointer;
хмм..

2021-02-15 19:22 UTC, Kettel1 commented on css/style.css
> +.proudct_features_btn::after, .proudct_features_btn::before {
исправил

2021-02-15 19:23 UTC, Kettel1 commented on css/style.css
> +    font-family: PT Sans;
исправил

2021-02-15 19:23 UTC, Kettel1 commented on css/style.css
> +    left: 0px;
вроде пробелы одинаковые тут..?

2021-02-15 19:50 UTC, Kettel1 commented on css/style.css
> +    padding: 10.7px 25px;
поправил) я через хром ровнял прост, не заметил даж)

2021-02-15 19:53 UTC, Kettel1 commented on css/style.css
> +    ;
Тут про двоеточие или про 21px и 0px? 0px обнуляет слева и справа дефолтные падинги, без которых все съезжает, вот это второе двоеточие появилось много где после css formater, он якобы помогает упорядочить css, больше проблем создал в итоге)

2021-02-16 04:56 UTC, Dima-Dim commented on catalog.html
> +                            <p class='header_account_name'>Равшан Джамшутович</p>
Ты делаешь тег p, потом имитируешь на нём какой-то интерактив. Тебя это не смущает? Всё что приходится имитировать, говорит что тут что-то не так. В данном случае не так то, что раз тут по стайлгайду инртерактив, то значит это либо кнопка, либо ссылка. По логике она ещё и совпадает с иконкой слева, стало быть всё это одна кнопка/ссылка.

2021-02-16 04:57 UTC, Dima-Dim commented on css/style.css
> +    ;
Лишнее `;` Ну и за одно излишняя точность в указании размеров.

2021-02-16 04:59 UTC, Dima-Dim commented on css/style.css
> +    left: 0px;
Где-то `0px`, где-то просто `0`. Это не единообразно. Лучше просто `0`.

2021-02-16 05:00 UTC, Dima-Dim commented on css/style.css
> +    ;
Про `;` ну и за одно `0px` нужно заменить на просто `0`.

2021-02-19 07:09 UTC, merged