Защита проекта.
htmlacademy-htmlcss/1651395-technomart-30 pull request #8
Opened 2021-02-22 13:50 UTC by Kettel1

Первые правки.
Поправил валидатор, изменил некоторые элементы, поправил по pixelperfect

2021-02-24 05:17 UTC, Dima-Dim requested changes
Проверь как выглядит опубликованная версия.
Как минимум нужно решить вопрос с https://up.htmlacademy.ru/htmlcss/30/criteries#b14
относительно https://github.com/htmlacademy-htmlcss/1651395-technomart-30/blob/master/css/Normalize.css

2021-02-28 12:27 UTC, Dima-Dim commented on css/style.css
>  h1, h2, h3, h4, h5, h6, p {
https://up.htmlacademy.ru/htmlcss/30/criteries#d25

2021-02-28 12:27 UTC, Dima-Dim commented on css/style.css
> +    font-family: 'Cuprum', sans-serif ;
https://up.htmlacademy.ru/htmlcss/30/criteries#b10

2021-02-28 12:27 UTC, Dima-Dim commented on css/style.css
> +    background-color: var(--secondary-color);      padding-left: 35px;
https://up.htmlacademy.ru/htmlcss/30/criteries#b15

2021-02-28 12:27 UTC, Dima-Dim commented on css/style.css
> +        position: relative;
https://up.htmlacademy.ru/htmlcss/30/criteries#b15

2021-02-28 12:27 UTC, Dima-Dim commented on css/style.css
> +    top: 0px;
https://up.htmlacademy.ru/htmlcss/30/criteries#b15

2021-02-28 12:27 UTC, Dima-Dim commented on css/style.css
> +    margin-top: 11.2px;
Точности до целых достаточно.

2021-02-28 12:27 UTC, Dima-Dim commented on css/style.css
> +    font-family: 'Cuprum','Arial', sans-serif;
Вижу что поправил.

2021-02-28 15:32 UTC, Kettel1 commented on css/style.css
>  h1, h2, h3, h4, h5, h6, p {
Уникальные теги документа: <⁠⁠⁠⁠html>, <body>?

2021-02-28 15:33 UTC, Kettel1 commented on css/style.css
>  h1, h2, h3, h4, h5, h6, p {
Там ведь есть исключения, body в них попадает

2021-02-28 15:38 UTC, Kettel1 commented on css/style.css
> +    top: 0px;
filter: drop-shadow(0px 4px 20px rgba(0, 0, 0, 0.15)); типа таких тегов нужно поправлять на 0 вместо 0px?

2021-02-28 17:08 UTC, Dima-Dim commented on css/style.css
>  h1, h2, h3, h4, h5, h6, p {
```
h1 это не body.
Неверно:
ul { list-style: none }
p { margin: 0 }
div { font-size: 80% }
* { margin: 0; padding: 0; }
```
Пересмотри лекцию про Оформление контента, там должны рассказывать чем чревата такая стилизация.

2021-02-28 17:10 UTC, Dima-Dim commented on css/style.css
> +    top: 0px;
Везде где 0 единицу исчисления указывать не нужно. Либо нужно. Но везде одинаково.

2021-02-28 19:53 UTC, Kettel1 commented on css/style.css
>  h1, h2, h3, h4, h5, h6, p {
аа, ты про h1, просто выделен тег body был

2021-02-28 20:08 UTC, Kettel1 commented on css/style.css
>  h1, h2, h3, h4, h5, h6, p {
поправил

2021-03-01 06:49 UTC, merged